### ISSUE TITLE
[ERROR] Bot encountered exception in Farming Mode when raid ends naturally

### ISSUE THREAD

**Issue by Deadfarmer** [steve1316/granblue-automation-pyautogui#101]
0:17:24 [ERROR] Bot encountered exception in Farming Mode: 
Traceback (most recent call last):
  File "Path\Desktop\GAA\backend\bot\game.py", line 895, in start_farming_mode
    Settings.item_amount_farmed += Raid.start(first_run)
  File "Path\Desktop\GAA\backend\bot\game_modes\raid.py", line 207, in start
    elif CombatMode.start_combat_mode():
  File "Path\Desktop\GAA\backend\bot\combat_mode.py", line 973, in start_combat_mode
    CombatMode._enable_auto()
  File "Path\Desktop\GAA\backend\bot\combat_mode.py", line 563, in _enable_auto
    enabled_semi_auto_button_location = ImageUtils.find_button("semi_button_enabled")
  File "Path\Desktop\GAA\backend\utils\image_utils.py", line 228, in find_button
    result_flag: bool = ImageUtils._match(template, custom_confidence)
  File "Path\Desktop\GAA\backend\utils\image_utils.py", line 94, in _match
    height, width = template.shape
AttributeError: 'NoneType' object has no attribute 'shape'

This occurs whenever the raid hits 0%, chests drop, and only the "NEXT" button is available.

**Comment by steve1316** [comment]
Some adjustments to Combat Mode has been made in the past few days. Has this problem come back in the latest version so far?

**Comment by Deadfarmer** [comment]
Still occuring, yes. On version 1.2.7. Easiest to replicate on very fast raids.

**Comment by steve1316** [comment]
v1.3.0 is out with a possible fix for this. I have not encountered this issue since so let me know if it happens again.
