### ISSUE TITLE
Error when use discord bot 

### ISSUE THREAD

**Issue by exodia0x** [steve1316/granblue-automation-pyautogui#124]
When I use discord notification it show error and force stop bot. I already test it's Run normal massage Test1234 to my discord

*(Running Bot and game in VMware Windows server 2019)*
Python Version 3.8.3

Traceback (most recent call last):
  File "backend/main.py", line 5, in <module>
    from bot.game import Game
  File "C:\Users\Administrator\Downloads\Granblue.Automation.v1.5.1\backend\bot\game.py", line 13, in <module>
    from utils.image_utils import ImageUtils
  File "C:\Users\Administrator\Downloads\Granblue.Automation.v1.5.1\backend\utils\image_utils.py", line 10, in <module>
    import easyocr
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\easyocr__init.py", line 1, in <module>
    from .easyocr import Reader
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\easyocr\easyocr.py", line 3, in <module>
    from .detection import get_detector, get_textbox
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\easyocr\detection.py", line 1, in <module>
    import torch
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch__init.py", line 117, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

Saved message log to: log 2022-03-23 14-19-29.txt
Child process finished with code 1

**Comment by steve1316** [comment]
Hmm try setting your VM to have 8gb of RAM in addition to maybe changing your paging file to be system-managed if it is not already.

**Comment by steve1316** [comment]
Were you able to fix this?
