### ISSUE TITLE
Guild Wars specific settings...

### ISSUE THREAD

**Issue by enustah28** [steve1316/granblue-automation-pyautogui#144]
I was farming a raid and faced this error after navigating to the rewards screen.

Probably due to Guild Wars specific settings that require checking the results.
This is only a report, not a request for a fix.

The environment is the latest version, Ver. 1.9.0, and has not been moved from its vanilla state.

 [ERROR] Bot encountered exception in Farming Mode: 
Traceback (most recent call last):
  File "E:\\Granblue.Automation\backend\bot\game.py", line 925, in start_farming_mode
    Raid.start(first_run)
  File "E:\\Granblue.Automation\backend\bot\game_modes\raid.py", line 189, in start
    Raid._navigate()
  File "E:\\Granblue.Automation\backend\bot\game_modes\raid.py", line 167, in _navigate
    Raid._join_raid()
  File "E:\\Granblue.Automation\backend\bot\game_modes\raid.py", line 110, in _join_raid
    elif Game.check_for_pending() is False:
  File "E:\\Granblue.Automation\backend\bot\game.py", line 798, in check_for_pending
    while Game._clear_pending_battle():
  File "E:\\Granblue.Automation\backend\bot\game.py", line 737, in _clear_pending_battle
    Game.collect_loot(is_completed = True)
  File "E:\\Granblue.Automation\backend\bot\game.py", line 578, in collect_loot
    temp_amount = ImageUtils.find_farmed_items(Settings.item_name)
  File "E:\\Granblue.Automation\backend\utils\image_utils.py", line 591, in find_farmed_items
    locations = ImageUtils.find_all(item_name, is_item = True, custom_confidence = 0.80)
  File "E:\\Granblue.Automation\backend\utils\image_utils.py", line 489, in find_all
    locations = ImageUtils._match_all(template, custom_confidence)
  File "E:\\Granblue.Automation\backend\utils\image_utils.py", line 157, in _match_all
    height, width = template.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by steve1316** [comment]
What item and raid were you trying to farm?

**Comment by enustah28** [comment]
That's Lvl 250 Belial with Cunning Devil's Horn.

**Comment by steve1316** [comment]
Need to convert the new image assets back from .webp to .jpg format.

**Comment by steve1316** [comment]
Fix in v1.9.1.
