### ISSUE TITLE
i got this error after start

### ISSUE THREAD

**Issue by lovemark1234** [steve1316/granblue-automation-pyautogui#158]
Traceback (most recent call last):
  File "backend/main.py", line 5, in <module>
    from bot.game import Game
  File "C:\Users\marks\Downloads\gf\backend\bot\game.py", line 7, in <module>
    import pyautogui
  File "C:\Users\marks\AppData\Local\Programs\Python\Python38\lib\site-packages\pyautogui\__init__.py", line 183, in <module>
    import pyscreeze
  File "C:\Users\marks\AppData\Local\Programs\Python\Python38\lib\site-packages\pyscreeze\__init__.py", line 45, in <module>
    import cv2, numpy
  File "C:\Users\marks\AppData\Local\Programs\Python\Python38\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\marks\AppData\Local\Programs\Python\Python38\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\marks\AppData\Local\Programs\Python\Python38\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\marks\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\marks\AppData\Local\Programs\Python\Python38\lib\site-packages\cv2\gapi\__init__.py", line 290, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

Saved message log to: log 2023-01-11 15-58-22.txt
Child process finished with code 1

[log 2023-01-11 15-58-22.txt](https://github.com/steve1316/granblue-automation-pyautogui/files/10389903/log.2023-01-11.15-58-22.txt)

**Comment by steve1316** [comment]
Just updated the installation steps with a link to the [new installation instructions page](https://github.com/steve1316/granblue-automation-pyautogui/wiki/Installation-Instructions) in the wiki.

Try out the section at the bottom for the `AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)` problem and let me know how it turns out!

**Comment by lovemark1234** [comment]
> Just updated the installation steps with a link to the [new installation instructions page](https://github.com/steve1316/granblue-automation-pyautogui/wiki/Installation-Instructions) in the wiki.
> 
> Try out the section at the bottom for the `AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)` problem and let me know how it turns out!

Thank ! solved after

pip install --upgrade pip setuptools wheel --user
pip install opencv-python
pip install -r requirements.txt
pip install "opencv-python-headless<4.3"

in backend folder
