### ISSUE TITLE
Proving grounds when second event option not working

### ISSUE THREAD

**Issue by plisquin** [steve1316/granblue-automation-pyautogui#163]
00:00:00 [INFO] Device dimensions: 1920x1080

00:00:00 ####################
00:00:00 ####################
00:00:00 [FARM] Starting Farming Mode for Proving Grounds.
00:00:00 [FARM] Farming 300x Repeated Runs at Extreme.
00:00:00 ####################
00:00:00 ####################

00:00:00 [PROVING.GROUNDS] Now beginning process to navigate to the mission: Extreme...

00:00:00 [DEBUG] Starting process to find the HOME header image...
00:00:00 [DEBUG] Match found with 0.983 >= 0.8 at Point {20.0, 57.0} using scale: 1.0.
00:00:00 [DEBUG] Current location confirmed to be at HOME.
00:00:00 [INFO] Bot is already at the Home screen.
00:00:00 [DEBUG] Now attempting to find and click the "home_menu" button.

00:00:00 [DEBUG] Starting process to find the HOME_MENU button image...
00:00:00 [DEBUG] Match found with 0.91 >= 0.8 at Point {931.0, 39.0} using scale: 1.0.
00:00:00 [DEBUG] Found the HOME_MENU at {1004.0, 90.0}.

00:00:01 [DEBUG] Starting process to find all EVENT_BANNER images...
00:00:02 [DEBUG] Match found with 0.869 >= 0.8 at Point {146.0, 1697.0} with scale: 1.0.
00:00:02 [DEBUG] Match not found with 0.6641741394996643 < 0.8 at Point {146.0, 1696.0} with scale: 1.0.
00:00:02 [DEBUG] Found match locations for event_banner: [{187.0, 1460.0}, {192.0, 1715.0}].

00:00:05 [DEBUG] Starting process to find the PROVING_GROUNDS header image...
00:00:05 [DEBUG] Match not found with 0.381 not >= 0.8 at Point {382.0, 46.0} using scale 1.0.
00:00:05 [DEBUG] Source bitmap is null. Moving the screen a bit and waiting a second before trying again.
00:00:07 [DEBUG] Match not found with 0.381 not >= 0.8 at Point {382.0, 46.0} using scale 1.0.
00:00:08 [DEBUG] Match not found with 0.381 not >= 0.8 at Point {382.0, 46.0} using scale 1.0.
00:00:08 [DEBUG] Source bitmap is null. Moving the screen a bit and waiting a second before trying again.
00:00:09 [DEBUG] Match not found with 0.381 not >= 0.8 at Point {382.0, 46.0} using scale 1.0.
00:00:10 [DEBUG] Match not found with 0.381 not >= 0.8 at Point {382.0, 46.0} using scale 1.0.
00:00:10 [WARNING] Failed to confirm the bot location at PROVING_GROUNDS.
00:00:10 GAA encountered an Exception: com.steve1316.granblue_automation_android.bot.game_modes.ProvingGrounds$ProvingGroundsException: Failed to arrive at Proving Grounds page.
	at com.steve1316.granblue_automation_android.bot.game_modes.ProvingGrounds.navigate(ProvingGrounds.kt:55)
	at com.steve1316.granblue_automation_android.bot.game_modes.ProvingGrounds.start(ProvingGrounds.kt:68)
	at com.steve1316.granblue_automation_android.bot.Game.start(Game.kt:1113)
	at com.steve1316.granblue_automation_android.StartModule.onStartEvent(StartModule.java:342)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
	at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:440)
	at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:421)
	at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:394)
	at org.greenrobot.eventbus.EventBus.post(EventBus.java:275)
	at org.greenrobot.eventbus.EventBus.postSticky(EventBus.java:316)
	at com.steve1316.automation_library.utils.BotService$onCreate$1$onTouch$1.invoke(BotService.kt:136)
	at com.steve1316.automation_library.utils.BotService$onCreate$1$onTouch$1.invoke(BotService.kt:120)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by steve1316** [comment]
Sending this over to the correct repo at https://github.com/steve1316/granblue-automation-android/issues/35.
