### ISSUE TITLE
Current event (token drawboxes) bug "IndexError: list index out of range" when trying to locate banner.

### ISSUE THREAD

**Issue by stijnvcp** [steve1316/granblue-automation-pyautogui#19]
```
0:00:00 [INFO] Initializing EasyOCR reader...
0:00:02 [INFO] EasyOCR reader initialized.
0:00:03 [SUCCESS] Bot's current location is at HOME.
0:00:03 [INFO] Bot is at the Home screen.

0:00:03 [DEBUG] Recalibrating the dimensions of the game window...
0:00:03 [SUCCESS] Found the HOME button at Point(x=1773, y=1002).
0:00:03 [SUCCESS] Found the HOME_NEWS button at Point(x=1375, y=107).
0:00:03 [SUCCESS] Found the HOME_MENU button at Point(x=1787, y=104).
0:00:03 [SUCCESS] Dimensions of the game window has been successfully recalibrated.

********************************************************************************
********************************************************************************
0:00:03 [INFO] Screen Size: Size(width=1920, height=1080)
0:00:03 [INFO] Game Window Dimensions: Region(1340, 80, 1750, 946)
********************************************************************************
********************************************************************************
0:00:03 [SUCCESS] Bot's current location is at HOME.


################################################################################
################################################################################
0:00:03 [FARM] Starting Farming Mode for Event (Token Drawboxes).
0:00:03 [FARM] Farming 20x Repeated Runs at VH Event Raid.
################################################################################
################################################################################

0:00:04 [SUCCESS] Bot's current location is at HOME.
0:00:04 [INFO] Bot is at the Home screen.
0:00:04 [SUCCESS] Bot's current location is at HOME.
0:00:04 [DEBUG] Attempting to find and click the button: "home_menu".
0:00:04 [SUCCESS] Found the HOME_MENU button at Point(x=1787, y=104).
0:00:05 [DEBUG] Failed to detect any occurrences of EVENT_BANNER images.
0:00:05 [DEBUG] Failed to detect any occurrences of EVENT_BANNER_BLUE images.

0:00:05 [ERROR] Bot encountered exception in MapSelection select_map(): 
Traceback (most recent call last):
  File "C:\Users\stijn\Desktop\granblue-automation-pyautogui-main\map_selection.py", line 543, in select_map
    self._game.mouse_tools.move_and_click_point(banner_locations[0][0], banner_locations[0][1])
IndexError: list index out of range


0:00:05 [ERROR] Bot encountered exception in Farming Mode: 
Traceback (most recent call last):
  File "C:\Users\stijn\Desktop\granblue-automation-pyautogui-main\game.py", line 1945, in start_farming_mode
    raise Exception("Confirming the location of the Summon Selection screen after selecting the mission returned False.")
Exception: Confirming the location of the Summon Selection screen after selecting the mission returned False.


################################################################################
################################################################################
0:00:05 [FARM] Ending Farming Mode.
################################################################################
################################################################################
```

Bug with the current drawbox event "The Divine Generals Assembly". It seems that it's unable to find the banner for the event.
Even though the banner is visible on the menu.
![image](https://user-images.githubusercontent.com/75256118/113146845-03aade00-91e5-11eb-929d-d3932bc90703.png)

**Comment by steve1316** [comment]
Thank you for letting me know. I must have messed up when I was fixing a related issue with the previous event. I will get right on this.

**Comment by steve1316** [comment]
Just updated the bot to fix the navigation issue for Event and Event (Token Drawboxes). Let me know how it goes!

**Comment by stijnvcp** [comment]
Bot goes to the event correctly now.

there's is another bug now though, I specified the bot needed to run the very hard raid, but the cursor was hovering the extreme mode and got stuck in this loop.
![image](https://user-images.githubusercontent.com/75256118/113337588-d4779800-92dc-11eb-91cb-f16987447a00.png)

**Comment by steve1316** [comment]
Thanks for letting me know. I just redid the template images for Very Hard, Extreme, and Impossible Raids so let me know how it turns out!

**Comment by steve1316** [comment]
Closing issue as the Event has ended.
