### ISSUE TITLE
unable to import pyscreeze

### ISSUE THREAD

**Issue by xswordcarsh** [steve1316/granblue-automation-pyautogui#204]
0:00:01 [ERROR] Bot encountered exception in Farming Mode: 

Traceback (most recent call last):

  File "C:\Users\HP PAVILION\Desktop\Automate\backend\bot\game.py", line 989, in start_farming_mode

    Game._calibrate_game_window(display_info_check = True)

  File "C:\Users\HP PAVILION\Desktop\Automate\backend\bot\game.py", line 54, in _calibrate_game_window

    Settings.home_button_location = ImageUtils.find_button("home", bypass_general_adjustment = True, tries = 1)

  File "C:\Users\HP PAVILION\Desktop\Automate\backend\utils\image_utils.py", line 494, in find_button

    result_flag: bool = ImageUtils._match(f"{ImageUtils._current_dir}/images/buttons/{image_name.lower()}.jpg", confidence = custom_confidence,

  File "C:\Users\HP PAVILION\Desktop\Automate\backend\utils\image_utils.py", line 146, in _match

    image: Image = pyautogui.screenshot()

  File "C:\Users\HP PAVILION\AppData\Local\Programs\Python\Python38\lib\site-packages\pyautogui\__init__.py", line 231, in _couldNotImportPyScreeze

    raise PyAutoGUIException(

pyautogui.PyAutoGUIException: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.
![Granblue_Automation_jBjGRjTwp5](https://github.com/steve1316/granblue-automation-pyautogui/assets/25261890/0ddf9dfc-c9c8-4787-9ada-70fbe94e7c80)

**Comment by xswordcarsh** [comment]
nvm found the issue

pip install --upgrade pyautogui
pip install --upgrade pillow

**Comment by steve1316** [comment]
Thanks for posting the solution. Added it to the [Wiki](https://github.com/steve1316/granblue-automation-pyautogui/wiki/Installation-Instructions) 👍

**Comment by agahvcn** [comment]
thank you man, you are amazing

**Comment by oded-nizan** [comment]
> nvm found the issue
> 
> pip install --upgrade pyautogui pip install --upgrade pillow

I have the same error and have attempted to fix it by upgrading pip as well as pyaoutogui, pillow and pyscreeze but unfortunately the problem has not been fixed. Would really appreciate any help
